spring:
  data:
    mongodb:
      uri: mongodb://192.168.2.2:27017/recommender
  redis:
    port: 6379
    host: 192.168.2.2
    timeout: 5000
    database: 0
    password:
  cache:
    cache-names:c1
server:
  port: 8080